[tasker.tasks.1]
name = "Example Task (repeating date check)"
cmd = "date"
args = []
interval = 4

[tasker.tasks.2]
name = "Example Task (repeating test message)"
cmd = "echo"
args = ["this is a test"]
interval = 10
