name: ci/cd

on:
  workflow_dispatch:
  push:
    branches: [ main, 'release/*' ]
  pull_request:
    branches: [ main, 'release/*' ]
  # Build once a month, just to be sure things are still working
  schedule:
    - cron: "49 4 26 * *"

jobs:

  core-builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: ['26.1']

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gnuplot
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Proper Tests
      run: rebar3 as test do compile, proper --regressions
    # - name: Run Tests
    #   run: rebar3 ct -c
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tall
    # - name: Test Coverage
    #   run: rebar3 as test do proper -c, cover -v --min_coverage=0

